blank_issues_enabled: true
contact_links:
  - name: Ara Community Discord
    url: https://discord.gg/ara
    about: Please join our Discord server for real-time support and community discussion.
  - name: Ask a Question
    url: https://github.com/Aradotso/.github/discussions
    about: Ask questions or start general discussions here.
